config/routes.rb
Fileupload::Application.routes.draw do

    devise_for :members do

   resources :users
    end 
   root :to => 'users#index'

     

end

app/models/ability.rb
 class Ability
  include CanCan::Ability

  def initialize(member)
    
    member ||= Member.new   #guest user (not logged in)
      if member.administrator?
        can :manage, :all
      else
        can  :read,   :all
        can  :create, :all
        can  :update, :all  
      end
     
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
    end
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:administrator
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  

  # Setup accessible (or protected) attributes for your model
  
    attr_accessible :name, :attach, :pic
    has_attached_file :pic, :styles => { :medium => "300x300>", :thumb => "100x100>" },
                      :storage => :dropbox,
                      :dropbox_credentials => "#{Rails.root}/config/dropbox.yml",
                      :dropbox_options => { 
                           :path => proc { |style| "photos/#{style}/#{id}_#{pic.original_filename}" }
                         }
                      

    has_attached_file :attach
   

	   validates :name, :presence => true
    # validates_attachment_presence :pic
     validates_attachment_size :pic, :less_than => 5.megabytes
     validates_attachment_content_type :pic, :content_type => [ 'image/jpg', 'image/jpeg', 'image/png']
    
     validate :pic_file_name_cannot_be_blank

     def pic_file_name_cannot_be_blank
     
       if attach_file_name.blank? and  pic_file_name.blank?
         errors.add(:pic_file_name,  "cannot be blank")
       end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

   rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  
end
 
  before_filter :authenticate_member! 
    def current_ability
    @current_ability ||= Ability.new(current_member)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  before_filter :authenticate_member!
  load_and_authorize_resource
  
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.email = current_member.email
    
   #logger.dubug "=============#{@user.inspect}"
    respond_to do |format|
      if @user.save
        #debugger
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
 
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class=" alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "File Upload Application", root_path, :class => 'brand' %>
<ul class="nav">
  <% if member_signed_in? %>
    <li>

    <%= link_to('Logout', destroy_member_session_path, :method=>'delete') %>
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_member_session_path)  %>
    </li>
  <% end %>
  <% if member_signed_in? %>
    <li>
    <%= link_to('Edit account', edit_member_registration_path) %>
    </li> 
    <li>
    <%= link_to('Sign up', new_member_registration_path)  %>
    </li>
  <% end %>
</ul>
<% if member_signed_in? %>
  <ul class="pull-right">
    <li><strong>Signed In As <%= current_member.email %></strong>
  </li>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "File Upload Applications" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "App_Name" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span6">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer >
          </br>
          </br>
          </br>
          </br>
          </br>
          </br>
<p><b>Developed By : Nostalgic Faizan </b></p>


          </footer>
        </div>
      </div> <!--! end of .container -->
    </div>
     <!--! end of #main -->
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :multipart => true } do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
      </h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" align='center'>
    <%= f.label :Name %>
    <%= f.text_field :name %>
   </div><br/><br/>

    <p align='center'>
       <b> Attachment </b>
       <%= f.file_field :attach  %>
   </p><br/><br/>
   
    <p align='center's>
      <b> Picture </b>
      <%= f.file_field :pic %>
   </p><br/><br/> 

   <div class="actions" align='center'>
      <%= f.submit :UPLOAD, :class=>'betaTextField btn btn-primary' %>
   </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User Profile </h1><br/><br/>

<%= render 'form' %>

<%= link_to 'Show', @user,:class => "btn btn-mini" %> |
<%= link_to 'Back', users_path,:class => "btn btn-mini" %>

app/views/users/index.html.erb
<h1> WELCOME TO FILE UPLOAD </h1><br/>
<h2 class ="span4"> Listing Users</h2><br/>

<table class="table span6 table-bordered table-condensed table-hover table-nonfluid">
  <tr>
    <th>Name</th>
    <th>Email</th>
    
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user,:class => "btn btn-mini" %></td>
   
    
    <% if user.email == current_member.email || current_member.administrator == true %>

      <td><%= link_to 'Edit', edit_user_path(user) ,:class => "btn btn-mini" %></td>
      <td><%= link_to 'Destroy', user,:class => "btn btn-mini btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
     </td>
    <% end %>
  </tr>
<% end %>
</table>
<br/>
<br/><br/><br/>
<div class ="span8">
<h4 >Do You want to Upload File?</h4><br/>
<%= link_to 'Click Here to Upload File ', new_user_path ,:class => "btn btn-primary" %><br/>
</div>

app/views/users/new.html.erb
<h2 align="center">New Users Please provide details for Uploading Files .</h2>
<br /><br />
<h1 align="center">Upload File</h1><br/><br/>

<%= render 'form' %><br/>
<br/><br/>
<%= link_to 'Back', users_path ,:class => "btn btn-mini" %></div>

app/views/users/show.html.erb
   <div class="well"><%= image_tag @user.pic.url(:thumb)%> </br></br>
       <%= link_to "Click To View full Image File", @user.pic.url , :target => "_blank"%> 
   </div> 

    <div class="well"> 
        <%= link_to "Click here to Display Text File Attached", @user.attach.url, :target => "_blank" %>
    </div>
    <% if @user.pic_file_name %>
  Pic Details
    <table class="table table-bordered table-condensed table-hover table-nonfluid">
      <tr>
         <th>Pic File Name </th> 
         <th>Pic File Content Type </th>
         <th>Pic File Size </th> 
         <th>Pic Updated At </th>
         </tr><tr> 
   <td><%= @user.pic_file_name %></td>
   <td> <%= @user.pic_content_type %></td>
   <td><%= @user.pic_file_size %></td>
   <td><%= @user.pic_updated_at %></td>
 </tr>
   </table>
   <% end %>
 

   <% if @user.attach_file_name %>

    Attachment Details :
    <table class="table table-bordered table-condensed table-hover table-nonfluid">
      <tr>
         <th>Attach File Name </th> 
         <th>Attach File Content Type</th>
         <th>Attach File Size</th> 
         <th>Attach Updated At</th>
         </tr><tr> 
   <td><%= @user.attach_file_name %></td>
   <td> <%= @user.attach_content_type %></td>
   <td><%= @user.attach_file_size %></td>
   <td> <%= @user.attach_updated_at %></td>
 </tr>
   </table>
 
  <% else %>
  
 <% end %>  
  <b>Uploaded By:</b>
  <b><%= @user.email %></b><br/><br/>

<div class="link">
  <!-- <% p current_member.administrator %>  -->
    <% if @user.email == current_member.email || current_member.administrator == true %>
<%= link_to 'Edit', edit_user_path(@user),:class => "btn btn-mini" %> 
<% end %>
| <%= link_to 'Back', users_path,:class => "btn btn-mini" %>
</div>